version: '3'
services:
  server:
    build: .
    ports:
    - "8000:8000"
  database:
    image: "postgres"
    env_file:
      - database.env
    volumes:
    - postgres:/var/lib/postgresql/data/


volumes:
  postgres:
